name: Build layer

# triggers
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]
  workflow_dispatch:
# jobs
jobs:
  build:
    runs-on: ubuntu-latest 
    steps:
      - name: Checkout
        uses: actions/checkout@v2
      - name: Init step
        run: 'mkdir -p dist/layer/python/lib/python3.8/site-packages'
      - name: CDK Synth
        uses: muldos/aws-cdk-action-for-python-project@master
        with:
          python_build_command: 'pip3 install -r requirements.txt -t dist/layer/python/lib/python3.8/site-packages'
          zip_command: 'zip -r dist/layer/third-parties-layer.zip dist/layer/python'
          cdk_command: 'npx cdk deploy'
          cdk_work_dir: 'deploy'
        env:
          AWS_ACCESS_KEY_ID: ${{ secrets.AWS_ACCESS_KEY_ID }}
          AWS_SECRET_ACCESS_KEY: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
          AWS_DEFAULT_REGION: 'eu-west-1'